"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.router = void 0;
const express_1 = require("express");
const rankingController_1 = require("../controllers/rankingController");
const router = (0, express_1.Router)();
exports.router = router;
const rankingController = new rankingController_1.RankingController();
router.post("/ranking", rankingController.handle);
router.get("/ranking", rankingController.show);
