development:
  adapter: sqlite3
  database: src/database/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: src/database/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: src/database/production.sqlite3
  pool: 5
  timeout: 5000